server:
  port: 7003

redis:
  connection: ${services.redis.baseUrl:redis://localhost:6379}

okHttpClient:
  retries:
    maxElapsedBackoffMs: 5000

endpoints:
  health:
    sensitive: false

# For options, see com.netflix.spinnaker.fiat.config.FiatServerConfigurationProperties

logging:
  config: classpath:logback-defaults.xml
  level:
    com.netflix.spinnaker.kork: DEBUG

spinnaker:
  extensibility:
    plugins-root-path: fiat-web/config
    plugins:
      Armory.FileResourceProvider:
        enabled: true
        extensions:
          armory.fileResource:
            config:
              path: /Users/danielpeach/dev/spinnaker/fiat/gradle.properties
